const SUPPORTED_MISSIONS = ["market", "bridge", "road_language"];
const SUPPORTED_AGES = ["4-6", "7-9", "10-12"];
const SUPPORTED_LANGUAGES = ["en", "hi", "mr"];

const text = (en, hi, mr) => ({ en, hi, mr });
const option = (id, label) => ({ id, label });

const catalog = {
  market: {
    title: text("Market Mission", "बाज़ार मिशन", "बाजार मोहीम"),
    objective: text("Use money, quantities, totals and change to complete a shopping list.", "खरीदारी पूरी करने के लिए पैसे, मात्रा, कुल और बाकी का उपयोग करें।", "खरेदी पूर्ण करण्यासाठी पैसे, संख्या, एकूण आणि सुट्टे पैसे वापरा."),
    scene: "market",
    ages: {
      "4-6": [
        { skill: "quantity_matching", prompt: text("The picnic needs 3 bananas. Choose the basket with exactly 3.", "पिकनिक के लिए 3 केले चाहिए। ठीक 3 वाला टोकरा चुनें।", "सहलीसाठी 3 केळी हवीत. नेमकी 3 असलेली टोपली निवडा."), options: [option("two", text("🍌🍌  2", "🍌🍌  2", "🍌🍌  2")), option("three", text("🍌🍌🍌  3", "🍌🍌🍌  3", "🍌🍌🍌  3")), option("four", text("🍌🍌🍌🍌  4", "🍌🍌🍌🍌  4", "🍌🍌🍌🍌  4"))], answer: "three", explanation: text("Count each banana once: 1, 2, 3. The middle basket matches the list.", "हर केले को एक बार गिनें: 1, 2, 3। बीच वाला टोकरा सही है।", "प्रत्येक केळे एकदा मोजा: 1, 2, 3. मधली टोपली योग्य आहे.") },
        { skill: "coin_value", prompt: text("An apple costs ₹5. Which coin pays exactly?", "एक सेब ₹5 का है। कौन-सा सिक्का ठीक भुगतान करता है?", "एक सफरचंद ₹5 चे आहे. नेमके पैसे कोणते नाणे देते?"), options: [option("2", text("₹2", "₹2", "₹2")), option("5", text("₹5", "₹5", "₹5")), option("10", text("₹10", "₹10", "₹10"))], answer: "5", explanation: text("Match the price tag 5 to the coin marked ₹5.", "कीमत 5 को ₹5 लिखे सिक्के से मिलाएँ।", "किंमत 5 ही ₹5 लिहिलेल्या नाण्याशी जुळवा.") },
        { skill: "simple_total", prompt: text("Milk is ₹4 and bread is ₹3. How much altogether?", "दूध ₹4 और ब्रेड ₹3 है। कुल कितना?", "दूध ₹4 आणि ब्रेड ₹3 आहे. एकूण किती?"), options: [option("6", text("₹6", "₹6", "₹6")), option("7", text("₹7", "₹7", "₹7")), option("8", text("₹8", "₹8", "₹8"))], answer: "7", explanation: text("Start at 4 and count on 3: 5, 6, 7. The total is ₹7.", "4 से आगे 3 गिनें: 5, 6, 7। कुल ₹7 है।", "4 पासून पुढे 3 मोजा: 5, 6, 7. एकूण ₹7.") },
      ],
      "7-9": [
        { skill: "multiplication_total", prompt: text("Buy 3 juice boxes at ₹12 each. What is the total?", "₹12 के 3 जूस बॉक्स खरीदें। कुल कितना है?", "प्रत्येकी ₹12 चे 3 ज्यूस बॉक्स घ्या. एकूण किती?"), options: [option("24", text("₹24", "₹24", "₹24")), option("36", text("₹36", "₹36", "₹36")), option("42", text("₹42", "₹42", "₹42"))], answer: "36", explanation: text("Three groups of 12 are 12 + 12 + 12 = ₹36.", "12 के तीन समूह: 12 + 12 + 12 = ₹36।", "12 चे तीन गट: 12 + 12 + 12 = ₹36.") },
        { skill: "budgeting", prompt: text("You have ₹50 after buying ₹36 of juice. Which ₹14 item uses the budget exactly?", "₹36 का जूस लेने के बाद आपके पास ₹50 का बजट है। कौन-सी ₹14 की वस्तु बजट पूरा उपयोग करती है?", "₹36 चा ज्यूस घेतल्यानंतर बजेट ₹50 आहे. कोणती ₹14 ची वस्तू बजेट नेमके वापरते?"), options: [option("fruit", text("Fruit cup ₹14", "फल कप ₹14", "फळ कप ₹14")), option("cake", text("Cake ₹20", "केक ₹20", "केक ₹20")), option("toy", text("Toy ₹25", "खिलौना ₹25", "खेळणे ₹25"))], answer: "fruit", explanation: text("₹50 − ₹36 leaves ₹14, so the ₹14 fruit cup stays within budget exactly.", "₹50 − ₹36 = ₹14 बचते हैं, इसलिए ₹14 का फल कप ठीक है।", "₹50 − ₹36 = ₹14 उरतात, म्हणून ₹14 चा फळ कप योग्य.") },
        { skill: "change", prompt: text("Your total is ₹36. You pay ₹50. Choose the correct change.", "कुल ₹36 है। आप ₹50 देते हैं। सही बाकी चुनें।", "एकूण ₹36 आहे. तुम्ही ₹50 देता. योग्य सुट्टे पैसे निवडा."), options: [option("12", text("₹12", "₹12", "₹12")), option("14", text("₹14", "₹14", "₹14")), option("16", text("₹16", "₹16", "₹16"))], answer: "14", explanation: text("Change is payment minus cost: ₹50 − ₹36 = ₹14.", "बाकी = भुगतान − लागत: ₹50 − ₹36 = ₹14।", "सुट्टे पैसे = दिलेले पैसे − किंमत: ₹50 − ₹36 = ₹14.") },
      ],
      "10-12": [
        { skill: "decimal_total", prompt: text("Rice costs ₹42.50 and lentils cost ₹27.25. Find the total.", "चावल ₹42.50 और दाल ₹27.25 की है। कुल निकालें।", "तांदूळ ₹42.50 आणि डाळ ₹27.25 आहे. एकूण काढा."), options: [option("69.75", text("₹69.75", "₹69.75", "₹69.75")), option("70.25", text("₹70.25", "₹70.25", "₹70.25")), option("68.75", text("₹68.75", "₹68.75", "₹68.75"))], answer: "69.75", explanation: text("Line up decimal places: 42.50 + 27.25 = ₹69.75.", "दशमलव मिलाएँ: 42.50 + 27.25 = ₹69.75।", "दशांश सरळ रेषेत मांडा: 42.50 + 27.25 = ₹69.75.") },
        { skill: "unit_price", prompt: text("Two 500 g packs cost ₹48 each. A 1 kg pack costs ₹90. Which is the better buy?", "दो 500 ग्राम पैक ₹48 प्रत्येक हैं। 1 किलो पैक ₹90 है। बेहतर खरीद कौन-सी है?", "दोन 500 ग्रॅम पाकिटे प्रत्येकी ₹48. 1 किलो पाकीट ₹90. चांगली खरेदी कोणती?"), options: [option("kilogram", text("1 kg pack", "1 किलो पैक", "1 किलो पाकीट")), option("two_halves", text("Two 500 g packs", "दो 500 ग्राम पैक", "दोन 500 ग्रॅम पाकिटे")), option("same", text("Same price", "एक ही कीमत", "समान किंमत"))], answer: "kilogram", explanation: text("Two small packs cost 2 × ₹48 = ₹96. The ₹90 pack saves ₹6 for the same 1 kg.", "दो छोटे पैक 2 × ₹48 = ₹96 हैं। ₹90 वाला 1 किलो पैक ₹6 बचाता है।", "दोन लहान पाकिटांची किंमत 2 × ₹48 = ₹96. ₹90 चे 1 किलो पाकीट ₹6 वाचवते.") },
        { skill: "budgeting_change", prompt: text("Your budget is ₹100 and the basket costs ₹69.75. What change remains?", "बजट ₹100 है और टोकरी ₹69.75 की है। कितने पैसे बचेंगे?", "बजेट ₹100 आणि टोपली ₹69.75 ची. किती पैसे उरतील?"), options: [option("30.25", text("₹30.25", "₹30.25", "₹30.25")), option("31.25", text("₹31.25", "₹31.25", "₹31.25")), option("29.75", text("₹29.75", "₹29.75", "₹29.75"))], answer: "30.25", explanation: text("Subtract the basket from the budget: ₹100.00 − ₹69.75 = ₹30.25.", "बजट में से लागत घटाएँ: ₹100.00 − ₹69.75 = ₹30.25।", "बजेटमधून किंमत वजा करा: ₹100.00 − ₹69.75 = ₹30.25.") },
      ],
    },
  },
  bridge: {
    title: text("Bridge Builder", "पुल निर्माता", "पूल बांधणी"), objective: text("Measure the gap and choose shapes and supports that make a safe bridge.", "अंतर मापें और सुरक्षित पुल के लिए आकार व सहारे चुनें।", "अंतर मोजा आणि सुरक्षित पुलासाठी आकार व आधार निवडा."), scene: "bridge",
    ages: {
      "4-6": [
        { skill: "shape_recognition", prompt: text("Which shape rolls away and is not a steady bridge block?", "कौन-सा आकार लुढ़क जाएगा और स्थिर पुल ब्लॉक नहीं है?", "कोणता आकार घरंगळेल आणि स्थिर पूल ठोकळा नाही?"), options: [option("circle", text("Circle", "गोला", "वर्तुळ")), option("square", text("Square", "वर्ग", "चौरस")), option("rectangle", text("Rectangle", "आयत", "आयत"))], answer: "circle", explanation: text("A circle has a curved edge, so it rolls. Flat-sided blocks stay steady.", "गोले का किनारा घुमावदार है, इसलिए वह लुढ़कता है। सपाट किनारे स्थिर रहते हैं।", "वर्तुळाची कड वाकडी असल्याने ते घरंगळते. सपाट कडा स्थिर राहतात.") },
        { skill: "length_comparison", prompt: text("The river gap is 4 footsteps. Which plank reaches across?", "नदी का अंतर 4 कदम है। कौन-सा तख्ता पार पहुँचेगा?", "नदीचे अंतर 4 पावले आहे. कोणती फळी पलीकडे पोहोचेल?"), options: [option("2", text("2 footsteps", "2 कदम", "2 पावले")), option("4", text("4 footsteps", "4 कदम", "4 पावले")), option("3", text("3 footsteps", "3 कदम", "3 पावले"))], answer: "4", explanation: text("The plank must be at least as long as the 4-footstep gap.", "तख्ता 4 कदम के अंतर जितना लंबा होना चाहिए।", "फळी 4 पावलांच्या अंतराइतकी लांब हवी.") },
        { skill: "pattern", prompt: text("Supports go: tall, short, tall, short. What comes next?", "सहारे हैं: लंबा, छोटा, लंबा, छोटा। आगे क्या आएगा?", "आधार: उंच, ठेंगणा, उंच, ठेंगणा. पुढे काय?"), options: [option("tall", text("Tall", "लंबा", "उंच")), option("short", text("छोटा", "छोटा", "ठेंगणा")), option("round", text("Round", "गोल", "गोल"))], answer: "tall", explanation: text("The two-part pattern repeats, so tall follows short.", "दो भाग का क्रम दोहरता है, इसलिए छोटे के बाद लंबा आता है।", "दोन भागांचा क्रम पुन्हा येतो, म्हणून ठेंगण्यानंतर उंच येतो.") },
      ],
      "7-9": [
        { skill: "measurement", prompt: text("The gap is 120 cm. Which beam reaches with the least waste?", "अंतर 120 सेमी है। सबसे कम बर्बादी में कौन-सी बीम पहुँचेगी?", "अंतर 120 सेमी. सर्वात कमी वाया जाणारी कोणती तुळई पोहोचेल?"), options: [option("100", text("100 cm", "100 सेमी", "100 सेमी")), option("120", text("120 cm", "120 सेमी", "120 सेमी")), option("150", text("150 cm", "150 सेमी", "150 सेमी"))], answer: "120", explanation: text("120 cm matches the measured gap exactly; 100 cm is short and 150 cm wastes material.", "120 सेमी ठीक अंतर के बराबर है; 100 छोटा और 150 में सामग्री बचेगी।", "120 सेमी अंतराशी नेमके जुळते; 100 कमी आणि 150 मध्ये साहित्य वाया जाते.") },
        { skill: "estimation", prompt: text("A 2 m bridge needs supports about every 50 cm. Estimate how many equal sections.", "2 मीटर पुल में लगभग हर 50 सेमी सहारा चाहिए। बराबर हिस्सों की संख्या अनुमान करें।", "2 मीटर पुलाला दर 50 सेमीवर आधार हवा. समान भाग किती?"), options: [option("2", text("2", "2", "2")), option("4", text("4", "4", "4")), option("5", text("5", "5", "5"))], answer: "4", explanation: text("2 m is 200 cm, and 200 ÷ 50 = 4 equal sections.", "2 मीटर = 200 सेमी, और 200 ÷ 50 = 4 बराबर हिस्से।", "2 मीटर = 200 सेमी, आणि 200 ÷ 50 = 4 समान भाग.") },
        { skill: "structural_shapes", prompt: text("Which brace shape helps stop a rectangular frame from wobbling?", "कौन-सा सहारा आयताकार फ्रेम को हिलने से रोकता है?", "कोणता आधार आयताकृती चौकट डळमळण्यापासून थांबवतो?"), options: [option("triangle", text("Triangle", "त्रिकोण", "त्रिकोण")), option("circle", text("Circle", "गोला", "वर्तुळ")), option("oval", text("Oval", "अंडाकार", "लंबवर्तुळ"))], answer: "triangle", explanation: text("A triangle holds its angles unless a side changes length, making a rigid brace.", "त्रिकोण के कोण स्थिर रहते हैं जब तक भुजा की लंबाई न बदले, इसलिए वह मजबूत सहारा है।", "बाजूची लांबी बदलल्याशिवाय त्रिकोणाचे कोन टिकतात, म्हणून तो मजबूत आधार आहे.") },
      ],
      "10-12": [
        { skill: "scale_measurement", prompt: text("On a 1:50 plan, the bridge is 8 cm long. What is its real length?", "1:50 नक्शे पर पुल 8 सेमी है। असली लंबाई क्या है?", "1:50 आराखड्यावर पूल 8 सेमी. खरी लांबी किती?"), options: [option("4m", text("4 m", "4 मीटर", "4 मीटर")), option("40m", text("40 m", "40 मीटर", "40 मीटर")), option("0.4m", text("0.4 m", "0.4 मीटर", "0.4 मीटर"))], answer: "4m", explanation: text("8 × 50 = 400 cm, and 400 cm = 4 m.", "8 × 50 = 400 सेमी, और 400 सेमी = 4 मीटर।", "8 × 50 = 400 सेमी, आणि 400 सेमी = 4 मीटर.") },
        { skill: "estimation_error", prompt: text("You estimated 3.8 m; the measured gap is 4 m. How far off was the estimate?", "अनुमान 3.8 मीटर था; मापा अंतर 4 मीटर है। अंतर कितना था?", "अंदाज 3.8 मीटर; मोजलेले अंतर 4 मीटर. अंदाज किती चुकला?"), options: [option("0.2", text("0.2 m", "0.2 मीटर", "0.2 मीटर")), option("0.8", text("0.8 m", "0.8 मीटर", "0.8 मीटर")), option("2", text("2 m", "2 मीटर", "2 मीटर"))], answer: "0.2", explanation: text("Absolute error is 4.0 − 3.8 = 0.2 m.", "पूर्ण त्रुटि 4.0 − 3.8 = 0.2 मीटर है।", "निरपेक्ष चूक 4.0 − 3.8 = 0.2 मीटर.") },
        { skill: "load_distribution", prompt: text("Where should two supports go to divide a 6 m beam into three equal spans?", "6 मीटर बीम को तीन बराबर हिस्सों में बाँटने के लिए दो सहारे कहाँ लगेंगे?", "6 मीटर तुळईचे तीन समान भाग करण्यासाठी दोन आधार कुठे?"), options: [option("2_4", text("At 2 m and 4 m", "2 और 4 मीटर पर", "2 आणि 4 मीटरवर")), option("1_5", text("At 1 m and 5 m", "1 और 5 मीटर पर", "1 आणि 5 मीटरवर")), option("3_4", text("At 3 m and 4 m", "3 और 4 मीटर पर", "3 आणि 4 मीटरवर"))], answer: "2_4", explanation: text("6 ÷ 3 = 2, so supports at 2 m and 4 m create three 2 m spans.", "6 ÷ 3 = 2, इसलिए 2 और 4 मीटर पर सहारे तीन 2 मीटर हिस्से बनाते हैं।", "6 ÷ 3 = 2, म्हणून 2 व 4 मीटरवरील आधार तीन 2 मीटर भाग करतात.") },
      ],
    },
  },
  road_language: {
    title: text("Road & Language", "सड़क और भाषा", "रस्ता आणि भाषा"), objective: text("Read signs, understand vocabulary and follow directions to reach the library.", "संकेत पढ़ें, शब्द समझें और पुस्तकालय तक दिशा का पालन करें।", "फलक वाचा, शब्द समजा आणि वाचनालयापर्यंत दिशा पाळा."), scene: "road",
    ages: {
      "4-6": [
        { skill: "sign_vocabulary", prompt: text("Which sign means STOP?", "कौन-सा संकेत रुकने को कहता है?", "कोणता फलक थांबायला सांगतो?"), options: [option("stop", text("🛑 STOP", "🛑 रुको", "🛑 थांबा")), option("go", text("🟢 GO", "🟢 जाओ", "🟢 जा")), option("school", text("🏫 SCHOOL", "🏫 स्कूल", "🏫 शाळा"))], answer: "stop", explanation: text("The red eight-sided STOP sign tells everyone to stop and look.", "लाल आठ किनारों वाला रुको संकेत सबको रुककर देखने को कहता है।", "लाल आठ बाजूंचा थांबा फलक सर्वांना थांबून पाहायला सांगतो.") },
        { skill: "direction_words", prompt: text("The library arrow points right. Which way should the explorer turn?", "पुस्तकालय का तीर दाईं ओर है। खोजी किस ओर मुड़े?", "वाचनालयाचा बाण उजवीकडे आहे. शोधकाने कुठे वळावे?"), options: [option("left", text("⬅️ Left", "⬅️ बायाँ", "⬅️ डावे")), option("right", text("➡️ Right", "➡️ दायाँ", "➡️ उजवे")), option("back", text("⬇️ Back", "⬇️ पीछे", "⬇️ मागे"))], answer: "right", explanation: text("Follow the arrowhead: it points to the right.", "तीर की नोक देखें: वह दाईं ओर है।", "बाणाचे टोक पाहा: ते उजवीकडे आहे.") },
        { skill: "sequence_comprehension", prompt: text("First stop, then look, then cross. What do you do after stopping?", "पहले रुकें, फिर देखें, फिर पार करें। रुकने के बाद क्या करें?", "आधी थांबा, मग पाहा, मग ओलांडा. थांबल्यावर काय?"), options: [option("look", text("Look", "देखें", "पाहा")), option("cross", text("Cross", "पार करें", "ओलांडा")), option("run", text("Run", "दौड़ें", "धावा"))], answer: "look", explanation: text("The instruction order is stop → look → cross, so looking is next.", "क्रम है रुको → देखो → पार करो, इसलिए अगला काम देखना है।", "क्रम थांबा → पाहा → ओलांडा, म्हणून पुढे पाहायचे.") },
      ],
      "7-9": [
        { skill: "sign_comprehension", prompt: text("A sign says: Library closed after 5 pm. It is 4:30 pm. What does this tell you?", "संकेत कहता है: पुस्तकालय शाम 5 के बाद बंद। समय 4:30 है। इसका क्या अर्थ है?", "फलक: वाचनालय संध्याकाळी 5 नंतर बंद. वेळ 4:30. अर्थ काय?"), options: [option("open", text("It should still be open", "अभी खुला होना चाहिए", "अजून खुले असावे")), option("closed", text("It is already closed", "पहले से बंद है", "आधीच बंद आहे")), option("unknown", text("The sign gives no clue", "संकेत नहीं बताता", "फलक सांगत नाही"))], answer: "open", explanation: text("4:30 pm is before 5 pm, so the stated closing time has not passed.", "4:30 शाम 5 से पहले है, इसलिए बंद होने का समय नहीं हुआ।", "4:30 ही 5 च्या आधी आहे, म्हणून बंद होण्याची वेळ झालेली नाही.") },
        { skill: "relative_directions", prompt: text("Face north, then turn right. Which direction are you facing?", "उत्तर की ओर देखकर दाएँ मुड़ें। अब किस दिशा में हैं?", "उत्तरेकडे तोंड करून उजवीकडे वळा. आता कोणती दिशा?"), options: [option("east", text("East", "पूर्व", "पूर्व")), option("west", text("West", "पश्चिम", "पश्चिम")), option("south", text("South", "दक्षिण", "दक्षिण"))], answer: "east", explanation: text("On a compass, east is to the right of north.", "कम्पास पर उत्तर के दाईं ओर पूर्व है।", "दिशादर्शकावर उत्तरेच्या उजवीकडे पूर्व आहे.") },
        { skill: "route_comprehension", prompt: text("Directions say: pass the park, turn left at the clinic, and stop beside the library. Where do you turn?", "निर्देश: पार्क पार करें, क्लिनिक पर बाएँ मुड़ें, पुस्तकालय के पास रुकें। कहाँ मुड़ें?", "सूचना: उद्यान ओलांडा, दवाखान्याजवळ डावे वळा, वाचनालयाशेजारी थांबा. कुठे वळाल?"), options: [option("clinic", text("At the clinic", "क्लिनिक पर", "दवाखान्याजवळ")), option("park", text("At the park", "पार्क पर", "उद्यानाजवळ")), option("library", text("At the library", "पुस्तकालय पर", "वाचनालयाजवळ"))], answer: "clinic", explanation: text("The phrase “turn left at the clinic” names the turning point directly.", "“क्लिनिक पर बाएँ मुड़ें” सीधे मुड़ने की जगह बताता है।", "“दवाखान्याजवळ डावे वळा” वळण्याची जागा थेट सांगते.") },
      ],
      "10-12": [
        { skill: "inference", prompt: text("The sign says: Diversion — bridge repairs; buses use River Road. Why is the usual route unavailable?", "संकेत: मार्ग परिवर्तन — पुल की मरम्मत; बसें नदी मार्ग लें। सामान्य रास्ता क्यों बंद है?", "फलक: वळण मार्ग — पूल दुरुस्ती; बसांनी नदी रस्ता वापरावा. नेहमीचा मार्ग का बंद?"), options: [option("repairs", text("The bridge is being repaired", "पुल की मरम्मत हो रही है", "पुलाची दुरुस्ती सुरू आहे")), option("festival", text("There is a festival", "त्योहार है", "उत्सव आहे")), option("weather", text("The weather is hot", "मौसम गर्म है", "हवामान गरम आहे"))], answer: "repairs", explanation: text("“Diversion” gives an alternate route, and “bridge repairs” states the reason.", "“मार्ग परिवर्तन” दूसरा रास्ता देता है और “पुल की मरम्मत” कारण बताता है।", "“वळण मार्ग” पर्यायी रस्ता देतो आणि “पूल दुरुस्ती” कारण सांगते.") },
        { skill: "multi_step_directions", prompt: text("Go east for two blocks, south for one, then west for one. Relative to your start, where are you?", "दो ब्लॉक पूर्व, एक दक्षिण, फिर एक पश्चिम जाएँ। शुरुआत से अब कहाँ हैं?", "दोन ब्लॉक पूर्व, एक दक्षिण, मग एक पश्चिम. सुरुवातीपासून कुठे?"), options: [option("se", text("One block east and one south", "एक ब्लॉक पूर्व और एक दक्षिण", "एक ब्लॉक पूर्व आणि एक दक्षिण")), option("sw", text("One block west and one south", "एक ब्लॉक पश्चिम और एक दक्षिण", "एक ब्लॉक पश्चिम आणि एक दक्षिण")), option("east", text("Two blocks east", "दो ब्लॉक पूर्व", "दोन ब्लॉक पूर्व"))], answer: "se", explanation: text("Two east minus one west leaves one east; the south move remains one block.", "दो पूर्व में से एक पश्चिम घटाने पर एक पूर्व बचता है; एक दक्षिण भी रहता है।", "दोन पूर्वातून एक पश्चिम वजा केल्यावर एक पूर्व उरतो; दक्षिणेकडे एक भाग राहतो.") },
        { skill: "context_vocabulary", prompt: text("A sign says PEDESTRIANS HAVE PRIORITY. What does priority mean here?", "संकेत कहता है पैदल यात्रियों को प्राथमिकता। यहाँ प्राथमिकता का अर्थ?", "फलक: पादचाऱ्यांना प्राधान्य. येथे प्राधान्य म्हणजे?"), options: [option("first", text("They should be allowed to go first", "उन्हें पहले जाने देना चाहिए", "त्यांना आधी जाऊ द्यावे")), option("fast", text("They must walk faster", "उन्हें तेज चलना चाहिए", "त्यांनी वेगाने चालावे")), option("pay", text("They must pay", "उन्हें भुगतान करना होगा", "त्यांनी पैसे द्यावे"))], answer: "first", explanation: text("Priority means being given attention or the right to go before others.", "प्राथमिकता का अर्थ दूसरों से पहले जाने का अधिकार है।", "प्राधान्य म्हणजे इतरांआधी जाण्याचा हक्क किंवा महत्त्व.") },
      ],
    },
  },
};

function normalizeLanguage(language) { return SUPPORTED_LANGUAGES.includes(language) ? language : "en"; }
function localize(value, language) { return value?.[normalizeLanguage(language)] || value?.en || ""; }

function publicMission(missionId, ageGroup, language = "en") {
  if (!SUPPORTED_MISSIONS.includes(missionId) || !SUPPORTED_AGES.includes(ageGroup)) return null;
  const mission = catalog[missionId];
  const lang = normalizeLanguage(language);
  return {
    id: missionId, scene: mission.scene, ageGroup,
    title: localize(mission.title, lang), objective: localize(mission.objective, lang),
    steps: mission.ages[ageGroup].map((step, index) => ({
      index, skill: step.skill, prompt: localize(step.prompt, lang),
      options: step.options.map((choice) => ({ id: choice.id, label: localize(choice.label, lang) })),
    })),
  };
}

function evaluateMissionAnswer({ missionId, ageGroup, stepIndex, answerId, language = "en" }) {
  if (!SUPPORTED_MISSIONS.includes(missionId) || !SUPPORTED_AGES.includes(ageGroup)) return null;
  const step = catalog[missionId].ages[ageGroup][Number(stepIndex)];
  if (!step || !step.options.some((choice) => choice.id === answerId)) return null;
  const correct = answerId === step.answer;
  const correctOption = step.options.find((choice) => choice.id === step.answer);
  return { correct, skill: step.skill, explanation: localize(step.explanation, language), correctAnswer: localize(correctOption.label, language) };
}

module.exports = { SUPPORTED_MISSIONS, SUPPORTED_AGES, SUPPORTED_LANGUAGES, publicMission, evaluateMissionAnswer };
